export const PWA_ERROR_CODES = {
  UNSUPPORTED: "PWA_UNSUPPORTED",
  MANIFEST_INVALID: "PWA_MANIFEST_INVALID",
  SERVICE_WORKER_UNAVAILABLE: "PWA_SERVICE_WORKER_UNAVAILABLE",
  SERVICE_WORKER_REGISTRATION_FAILED: "PWA_SERVICE_WORKER_REGISTRATION_FAILED",
  SERVICE_WORKER_UPDATE_FAILED: "PWA_SERVICE_WORKER_UPDATE_FAILED",
  CACHE_INITIALIZATION_FAILED: "PWA_CACHE_INITIALIZATION_FAILED",
  PRIVATE_CACHE_CLEANUP_FAILED: "PWA_PRIVATE_CACHE_CLEANUP_FAILED",
  OFFLINE: "PWA_OFFLINE",
  INSTALL_NOT_AVAILABLE: "PWA_INSTALL_NOT_AVAILABLE",
  INSTALL_DISMISSED: "PWA_INSTALL_DISMISSED",
  UPDATE_AVAILABLE: "PWA_UPDATE_AVAILABLE",
  UPDATE_RELOAD_FAILED: "PWA_UPDATE_RELOAD_FAILED",
  SIGNED_URL_CACHE_BLOCKED: "PWA_SIGNED_URL_CACHE_BLOCKED",
  TOKEN_CACHE_BLOCKED: "PWA_TOKEN_CACHE_BLOCKED",
  OFFLINE_EDIT_UNSUPPORTED: "PWA_OFFLINE_EDIT_UNSUPPORTED",
  UNKNOWN_ERROR: "PWA_UNKNOWN_ERROR",
} as const;

export type PwaErrorCode = (typeof PWA_ERROR_CODES)[keyof typeof PWA_ERROR_CODES];

export class PwaDomainError extends Error {
  readonly code: PwaErrorCode;
  readonly retryable: boolean;

  constructor(code: PwaErrorCode, message: string, retryable: boolean = false) {
    super(message);
    this.name = "PwaDomainError";
    this.code = code;
    this.retryable = retryable;
  }
}
