/**
 * ==============================================================================
 * AUTO-GENERATED SUPABASE DATABASE TYPES
 * ==============================================================================
 * Do not edit this file manually.
 * Generate with command: `npm run supabase:types`
 * Generated from: GenViet Core Database Schema (P07 Baseline)
 * ==============================================================================
 */

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export type Database = {
  _system: {
    Tables: {
      infrastructure_status: {
        Row: {
          id: string;
          phase_code: string;
          initialized_at: string;
          version: string;
        };
        Insert: {
          id?: string;
          phase_code?: string;
          initialized_at?: string;
          version?: string;
        };
        Update: {
          id?: string;
          phase_code?: string;
          initialized_at?: string;
          version?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      normalize_person_name: {
        Args: {
          input_text: string;
        };
        Returns: string;
      };
    };
    Enums: {
      [_ in never]: never;
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          display_name: string;
          avatar_path: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          display_name: string;
          avatar_path?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          display_name?: string;
          avatar_path?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      family_trees: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          status: Database["public"]["Enums"]["tree_status"];
          privacy_level: Database["public"]["Enums"]["tree_privacy_level"];
          generation_anchor_person_id: string | null;
          created_by: string | null;
          updated_by: string | null;
          deleted_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          version: number;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["tree_status"];
          privacy_level?: Database["public"]["Enums"]["tree_privacy_level"];
          generation_anchor_person_id?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          version?: number;
        };
        Update: {
          id?: string;
          name?: string;
          description?: string | null;
          status?: Database["public"]["Enums"]["tree_status"];
          privacy_level?: Database["public"]["Enums"]["tree_privacy_level"];
          generation_anchor_person_id?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "fk_family_trees_generation_anchor";
            columns: ["id", "generation_anchor_person_id"];
            isOneToOne: false;
            referencedRelation: "persons";
            referencedColumns: ["tree_id", "id"];
          },
        ];
      };
      tree_memberships: {
        Row: {
          id: string;
          tree_id: string;
          user_id: string;
          role: Database["public"]["Enums"]["membership_role"];
          status: Database["public"]["Enums"]["membership_status"];
          created_by: string | null;
          updated_by: string | null;
          deleted_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          version: number;
        };
        Insert: {
          id?: string;
          tree_id: string;
          user_id: string;
          role?: Database["public"]["Enums"]["membership_role"];
          status?: Database["public"]["Enums"]["membership_status"];
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          version?: number;
        };
        Update: {
          id?: string;
          tree_id?: string;
          user_id?: string;
          role?: Database["public"]["Enums"]["membership_role"];
          status?: Database["public"]["Enums"]["membership_status"];
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "tree_memberships_tree_id_fkey";
            columns: ["tree_id"];
            isOneToOne: false;
            referencedRelation: "family_trees";
            referencedColumns: ["id"];
          },
        ];
      };
      persons: {
        Row: {
          id: string;
          tree_id: string;
          full_name: string;
          normalized_name: string;
          gender: Database["public"]["Enums"]["gender_type"];
          living_status: Database["public"]["Enums"]["living_status_type"];
          birth_date: string | null;
          birth_year: number | null;
          birth_date_precision: Database["public"]["Enums"]["date_precision_type"];
          birth_is_estimated: boolean;
          death_date: string | null;
          death_year: number | null;
          death_date_precision: Database["public"]["Enums"]["date_precision_type"];
          death_is_estimated: boolean;
          birth_place_text: string | null;
          death_place_text: string | null;
          hometown_text: string | null;
          burial_place_text: string | null;
          occupation_text: string | null;
          biography: string | null;
          verification_status: Database["public"]["Enums"]["verification_status_type"];
          avatar_path: string | null;
          created_by: string | null;
          updated_by: string | null;
          deleted_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          version: number;
        };
        Insert: {
          id?: string;
          tree_id: string;
          full_name: string;
          normalized_name?: string;
          gender?: Database["public"]["Enums"]["gender_type"];
          living_status?: Database["public"]["Enums"]["living_status_type"];
          birth_date?: string | null;
          birth_year?: number | null;
          birth_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          birth_is_estimated?: boolean;
          death_date?: string | null;
          death_year?: number | null;
          death_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          death_is_estimated?: boolean;
          birth_place_text?: string | null;
          death_place_text?: string | null;
          hometown_text?: string | null;
          burial_place_text?: string | null;
          occupation_text?: string | null;
          biography?: string | null;
          verification_status?: Database["public"]["Enums"]["verification_status_type"];
          avatar_path?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          version?: number;
        };
        Update: {
          id?: string;
          tree_id?: string;
          full_name?: string;
          normalized_name?: string;
          gender?: Database["public"]["Enums"]["gender_type"];
          living_status?: Database["public"]["Enums"]["living_status_type"];
          birth_date?: string | null;
          birth_year?: number | null;
          birth_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          birth_is_estimated?: boolean;
          death_date?: string | null;
          death_year?: number | null;
          death_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          death_is_estimated?: boolean;
          birth_place_text?: string | null;
          death_place_text?: string | null;
          hometown_text?: string | null;
          burial_place_text?: string | null;
          occupation_text?: string | null;
          biography?: string | null;
          verification_status?: Database["public"]["Enums"]["verification_status_type"];
          avatar_path?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "persons_tree_id_fkey";
            columns: ["tree_id"];
            isOneToOne: false;
            referencedRelation: "family_trees";
            referencedColumns: ["id"];
          },
        ];
      };
      person_avatars: {
        Row: {
          id: string;
          tree_id: string;
          person_id: string;
          bucket_id: string;
          object_path: string;
          thumbnail_path: string;
          original_filename: string | null;
          mime_type: string;
          size_bytes: number;
          width: number | null;
          height: number | null;
          status: string;
          created_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
        };
        Insert: {
          id?: string;
          tree_id: string;
          person_id: string;
          bucket_id?: string;
          object_path: string;
          thumbnail_path: string;
          original_filename?: string | null;
          mime_type: string;
          size_bytes: number;
          width?: number | null;
          height?: number | null;
          status?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Update: {
          id?: string;
          tree_id?: string;
          person_id?: string;
          bucket_id?: string;
          object_path?: string;
          thumbnail_path?: string;
          original_filename?: string | null;
          mime_type?: string;
          size_bytes?: number;
          width?: number | null;
          height?: number | null;
          status?: string;
          created_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "person_avatars_person_id_fkey";
            columns: ["person_id"];
            isOneToOne: false;
            referencedRelation: "persons";
            referencedColumns: ["id"];
          },
          {
            foreignKeyName: "person_avatars_tree_id_fkey";
            columns: ["tree_id"];
            isOneToOne: false;
            referencedRelation: "family_trees";
            referencedColumns: ["id"];
          },
        ];
      };
      parent_child_relationships: {
        Row: {
          id: string;
          tree_id: string;
          parent_id: string;
          child_id: string;
          parent_role: Database["public"]["Enums"]["parent_role_type"];
          relationship_kind: Database["public"]["Enums"]["relationship_kind_type"];
          verification_status: Database["public"]["Enums"]["verification_status_type"];
          notes: string | null;
          created_by: string | null;
          updated_by: string | null;
          deleted_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          version: number;
        };
        Insert: {
          id?: string;
          tree_id: string;
          parent_id: string;
          child_id: string;
          parent_role?: Database["public"]["Enums"]["parent_role_type"];
          relationship_kind?: Database["public"]["Enums"]["relationship_kind_type"];
          verification_status?: Database["public"]["Enums"]["verification_status_type"];
          notes?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          version?: number;
        };
        Update: {
          id?: string;
          tree_id?: string;
          parent_id?: string;
          child_id?: string;
          parent_role?: Database["public"]["Enums"]["parent_role_type"];
          relationship_kind?: Database["public"]["Enums"]["relationship_kind_type"];
          verification_status?: Database["public"]["Enums"]["verification_status_type"];
          notes?: string | null;
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "fk_parent_child_parent";
            columns: ["tree_id", "parent_id"];
            isOneToOne: false;
            referencedRelation: "persons";
            referencedColumns: ["tree_id", "id"];
          },
          {
            foreignKeyName: "fk_parent_child_child";
            columns: ["tree_id", "child_id"];
            isOneToOne: false;
            referencedRelation: "persons";
            referencedColumns: ["tree_id", "id"];
          },
        ];
      };
      unions: {
        Row: {
          id: string;
          tree_id: string;
          status: Database["public"]["Enums"]["union_status_type"];
          start_date: string | null;
          start_year: number | null;
          start_date_precision: Database["public"]["Enums"]["date_precision_type"];
          end_date: string | null;
          end_year: number | null;
          end_date_precision: Database["public"]["Enums"]["date_precision_type"];
          notes: string | null;
          verification_status: Database["public"]["Enums"]["verification_status_type"];
          created_by: string | null;
          updated_by: string | null;
          deleted_by: string | null;
          created_at: string;
          updated_at: string;
          deleted_at: string | null;
          version: number;
        };
        Insert: {
          id?: string;
          tree_id: string;
          status?: Database["public"]["Enums"]["union_status_type"];
          start_date?: string | null;
          start_year?: number | null;
          start_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          end_date?: string | null;
          end_year?: number | null;
          end_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          notes?: string | null;
          verification_status?: Database["public"]["Enums"]["verification_status_type"];
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          version?: number;
        };
        Update: {
          id?: string;
          tree_id?: string;
          status?: Database["public"]["Enums"]["union_status_type"];
          start_date?: string | null;
          start_year?: number | null;
          start_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          end_date?: string | null;
          end_year?: number | null;
          end_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          notes?: string | null;
          verification_status?: Database["public"]["Enums"]["verification_status_type"];
          created_by?: string | null;
          updated_by?: string | null;
          deleted_by?: string | null;
          created_at?: string;
          updated_at?: string;
          deleted_at?: string | null;
          version?: number;
        };
        Relationships: [
          {
            foreignKeyName: "unions_tree_id_fkey";
            columns: ["tree_id"];
            isOneToOne: false;
            referencedRelation: "family_trees";
            referencedColumns: ["id"];
          },
        ];
      };
      union_members: {
        Row: {
          id: string;
          tree_id: string;
          union_id: string;
          person_id: string;
          member_role: Database["public"]["Enums"]["union_member_role_type"];
          created_by: string | null;
          created_at: string;
          deleted_at: string | null;
          deleted_by: string | null;
        };
        Insert: {
          id?: string;
          tree_id: string;
          union_id: string;
          person_id: string;
          member_role?: Database["public"]["Enums"]["union_member_role_type"];
          created_by?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Update: {
          id?: string;
          tree_id?: string;
          union_id?: string;
          person_id?: string;
          member_role?: Database["public"]["Enums"]["union_member_role_type"];
          created_by?: string | null;
          created_at?: string;
          deleted_at?: string | null;
          deleted_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: "fk_union_members_union";
            columns: ["tree_id", "union_id"];
            isOneToOne: false;
            referencedRelation: "unions";
            referencedColumns: ["tree_id", "id"];
          },
          {
            foreignKeyName: "fk_union_members_person";
            columns: ["tree_id", "person_id"];
            isOneToOne: false;
            referencedRelation: "persons";
            referencedColumns: ["tree_id", "id"];
          },
        ];
      };
      audit_logs: {
        Row: {
          id: string;
          tree_id: string;
          actor_user_id: string | null;
          actor_name_cached: string | null;
          entity_type: string;
          entity_id: string;
          action_type: string;
          before_data: Json | null;
          after_data: Json | null;
          changed_fields: string[] | null;
          reason: string | null;
          request_id: string | null;
          source: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          tree_id: string;
          actor_user_id?: string | null;
          actor_name_cached?: string | null;
          entity_type: string;
          entity_id: string;
          action_type: string;
          before_data?: Json | null;
          after_data?: Json | null;
          changed_fields?: string[] | null;
          reason?: string | null;
          request_id?: string | null;
          source?: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          tree_id?: string;
          actor_user_id?: string | null;
          actor_name_cached?: string | null;
          entity_type?: string;
          entity_id?: string;
          action_type?: string;
          before_data?: Json | null;
          after_data?: Json | null;
          changed_fields?: string[] | null;
          reason?: string | null;
          request_id?: string | null;
          source?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "audit_logs_tree_id_fkey";
            columns: ["tree_id"];
            isOneToOne: false;
            referencedRelation: "family_trees";
            referencedColumns: ["id"];
          },
        ];
      };
      system_heartbeats: {
        Row: {
          id: string;
          last_heartbeat_at: string;
          last_source: string;
          last_run_id: string | null;
          last_status: string;
          last_duration_ms: number | null;
          last_error_code: string | null;
          consecutive_failures: number;
          last_success_at: string | null;
          last_failure_at: string | null;
          updated_at: string;
        };
        Insert: {
          id?: string;
          last_heartbeat_at?: string;
          last_source?: string;
          last_run_id?: string | null;
          last_status?: string;
          last_duration_ms?: number | null;
          last_error_code?: string | null;
          consecutive_failures?: number;
          last_success_at?: string | null;
          last_failure_at?: string | null;
          updated_at?: string;
        };
        Update: {
          id?: string;
          last_heartbeat_at?: string;
          last_source?: string;
          last_run_id?: string | null;
          last_status?: string;
          last_duration_ms?: number | null;
          last_error_code?: string | null;
          consecutive_failures?: number;
          last_success_at?: string | null;
          last_failure_at?: string | null;
          updated_at?: string;
        };
        Relationships: [];
      };
    };
    Views: {
      [_ in never]: never;
    };
    Functions: {
      record_system_heartbeat: {
        Args: {
          p_source?: string;
          p_run_id?: string | null;
          p_duration_ms?: number | null;
          p_status?: string;
          p_error_code?: string | null;
        };
        Returns: Database["public"]["Tables"]["system_heartbeats"]["Row"];
      };
      create_family_tree: {
        Args: {
          p_name: string;
          p_description?: string | null;
          p_privacy_level?: Database["public"]["Enums"]["tree_privacy_level"];
        };
        Returns: string;
      };
      restore_family_tree: {
        Args: {
          p_tree_id: string;
        };
        Returns: boolean;
      };
      restore_person: {
        Args: {
          p_person_id: string;
          p_expected_version?: number | null;
        };
        Returns: boolean;
      };
      create_person_with_parent_relationship: {
        Args: {
          p_tree_id: string;
          p_child_id: string;
          p_full_name: string;
          p_gender?: Database["public"]["Enums"]["gender_type"];
          p_living_status?: Database["public"]["Enums"]["living_status_type"];
          p_birth_date?: string | null;
          p_birth_year?: number | null;
          p_birth_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          p_birth_is_estimated?: boolean;
          p_death_date?: string | null;
          p_death_year?: number | null;
          p_death_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          p_death_is_estimated?: boolean;
          p_birth_place_text?: string | null;
          p_death_place_text?: string | null;
          p_hometown_text?: string | null;
          p_burial_place_text?: string | null;
          p_occupation_text?: string | null;
          p_biography?: string | null;
          p_parent_role?: Database["public"]["Enums"]["parent_role_type"];
          p_relationship_kind?: Database["public"]["Enums"]["relationship_kind_type"];
          p_verification_status?: Database["public"]["Enums"]["verification_status_type"];
          p_confirm_warnings?: boolean;
        };
        Returns: { person_id: string; relationship_id: string };
      };
      link_existing_parent: {
        Args: {
          p_tree_id: string;
          p_parent_id: string;
          p_child_id: string;
          p_parent_role?: Database["public"]["Enums"]["parent_role_type"];
          p_relationship_kind?: Database["public"]["Enums"]["relationship_kind_type"];
          p_verification_status?: Database["public"]["Enums"]["verification_status_type"];
          p_confirm_warnings?: boolean;
        };
        Returns: string;
      };
      create_person_with_child_relationship: {
        Args: {
          p_tree_id: string;
          p_parent_id: string;
          p_full_name: string;
          p_gender?: Database["public"]["Enums"]["gender_type"];
          p_living_status?: Database["public"]["Enums"]["living_status_type"];
          p_birth_date?: string | null;
          p_birth_year?: number | null;
          p_birth_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          p_birth_is_estimated?: boolean;
          p_death_date?: string | null;
          p_death_year?: number | null;
          p_death_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          p_death_is_estimated?: boolean;
          p_birth_place_text?: string | null;
          p_death_place_text?: string | null;
          p_hometown_text?: string | null;
          p_burial_place_text?: string | null;
          p_occupation_text?: string | null;
          p_biography?: string | null;
          p_parent_role?: Database["public"]["Enums"]["parent_role_type"];
          p_relationship_kind?: Database["public"]["Enums"]["relationship_kind_type"];
          p_verification_status?: Database["public"]["Enums"]["verification_status_type"];
          p_other_parent_id?: string | null;
          p_other_parent_role?: Database["public"]["Enums"]["parent_role_type"];
          p_other_relationship_kind?: Database["public"]["Enums"]["relationship_kind_type"];
          p_confirm_warnings?: boolean;
        };
        Returns: { person_id: string; relationship_id: string; other_relationship_id?: string };
      };
      link_existing_child: {
        Args: {
          p_tree_id: string;
          p_parent_id: string;
          p_child_id: string;
          p_parent_role?: Database["public"]["Enums"]["parent_role_type"];
          p_relationship_kind?: Database["public"]["Enums"]["relationship_kind_type"];
          p_verification_status?: Database["public"]["Enums"]["verification_status_type"];
          p_confirm_warnings?: boolean;
        };
        Returns: string;
      };
      replace_parent_relationship: {
        Args: {
          p_tree_id: string;
          p_old_relationship_id: string;
          p_old_expected_version: number;
          p_new_parent_id: string;
          p_child_id: string;
          p_parent_role?: Database["public"]["Enums"]["parent_role_type"];
          p_relationship_kind?: Database["public"]["Enums"]["relationship_kind_type"];
          p_verification_status?: Database["public"]["Enums"]["verification_status_type"];
          p_confirm_warnings?: boolean;
        };
        Returns: string;
      };
      soft_delete_parent_child_relationship: {
        Args: {
          p_relationship_id: string;
          p_expected_version: number;
        };
        Returns: boolean;
      };
      create_union_with_new_person: {
        Args: {
          p_tree_id: string;
          p_subject_person_id: string;
          p_full_name: string;
          p_gender?: Database["public"]["Enums"]["gender_type"];
          p_living_status?: Database["public"]["Enums"]["living_status_type"];
          p_birth_date?: string | null;
          p_birth_year?: number | null;
          p_birth_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          p_birth_is_estimated?: boolean;
          p_death_date?: string | null;
          p_death_year?: number | null;
          p_death_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          p_death_is_estimated?: boolean;
          p_hometown_text?: string | null;
          p_occupation_text?: string | null;
          p_biography?: string | null;
          p_subject_member_role?: Database["public"]["Enums"]["union_member_role_type"];
          p_partner_member_role?: Database["public"]["Enums"]["union_member_role_type"];
          p_union_status?: Database["public"]["Enums"]["union_status_type"];
          p_start_date?: string | null;
          p_start_year?: number | null;
          p_start_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          p_confirm_warnings?: boolean;
        };
        Returns: { person_id: string; union_id: string };
      };
      create_union_with_existing_person: {
        Args: {
          p_tree_id: string;
          p_person_1_id: string;
          p_person_2_id: string;
          p_member_1_role?: Database["public"]["Enums"]["union_member_role_type"];
          p_member_2_role?: Database["public"]["Enums"]["union_member_role_type"];
          p_union_status?: Database["public"]["Enums"]["union_status_type"];
          p_start_date?: string | null;
          p_start_year?: number | null;
          p_start_date_precision?: Database["public"]["Enums"]["date_precision_type"];
          p_confirm_warnings?: boolean;
        };
        Returns: string;
      };
      end_union: {
        Args: {
          p_union_id: string;
          p_expected_version: number;
          p_new_status: Database["public"]["Enums"]["union_status_type"];
          p_end_date?: string | null;
          p_end_year?: number | null;
          p_end_date_precision?: Database["public"]["Enums"]["date_precision_type"];
        };
        Returns: boolean;
      };
      soft_delete_union: {
        Args: {
          p_union_id: string;
          p_expected_version: number;
        };
        Returns: boolean;
      };
      get_tree_graph_slice: {
        Args: {
          p_tree_id: string;
          p_center_person_id: string;
          p_ancestor_depth?: number;
          p_descendant_depth?: number;
          p_include_spouses?: boolean;
          p_include_unverified?: boolean;
        };
        Returns: Record<string, unknown>;
      };
      record_audit_event: {
        Args: {
          p_tree_id: string;
          p_entity_type: string;
          p_entity_id: string;
          p_action_type: string;
          p_before_data?: Json | null;
          p_after_data?: Json | null;
          p_changed_fields?: string[] | null;
          p_reason?: string | null;
          p_source?: string;
          p_request_id?: string | null;
        };
        Returns: string;
      };
      restore_parent_child_relationship: {
        Args: {
          p_relationship_id: string;
          p_expected_version?: number | null;
        };
        Returns: boolean;
      };
      restore_union: {
        Args: {
          p_union_id: string;
          p_expected_version?: number | null;
        };
        Returns: boolean;
      };
      export_family_tree_backup: {
        Args: {
          p_tree_id: string;
        };
        Returns: Json;
      };
      import_family_tree_backup: {
        Args: {
          p_backup_data: Json;
        };
        Returns: Json;
      };
    };
    Enums: {
      tree_status: "active" | "archived";
      tree_privacy_level: "private" | "public";
      membership_role: "owner" | "admin" | "editor" | "viewer";
      membership_status: "active" | "invited" | "suspended";
      gender_type: "male" | "female" | "other" | "unknown";
      living_status_type: "living" | "deceased" | "unknown";
      date_precision_type: "exact" | "year" | "unknown";
      verification_status_type: "unverified" | "verified" | "disputed";
      parent_role_type: "father" | "mother" | "unspecified";
      relationship_kind_type: "biological" | "adoptive" | "step" | "foster";
      union_status_type: "active" | "separated" | "divorced" | "widowed" | "former";
      union_member_role_type: "spouse" | "partner" | "unspecified";
    };
    CompositeTypes: {
      [_ in never]: never;
    };
  };
};

type PublicSchema = Database[Extract<keyof Database, "public">];

export type Tables<
  PublicTableNameOrOptions extends
    keyof (PublicSchema["Tables"] & PublicSchema["Views"]) | { schema: keyof Database },
  TableName extends (PublicTableNameOrOptions extends { schema: keyof Database }
    ? keyof (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
        Database[PublicTableNameOrOptions["schema"]]["Views"])
    : never) = never,
> = PublicTableNameOrOptions extends { schema: keyof Database }
  ? (Database[PublicTableNameOrOptions["schema"]]["Tables"] &
      Database[PublicTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R;
    }
    ? R
    : never
  : PublicTableNameOrOptions extends keyof (PublicSchema["Tables"] & PublicSchema["Views"])
    ? (PublicSchema["Tables"] & PublicSchema["Views"])[PublicTableNameOrOptions] extends {
        Row: infer R;
      }
      ? R
      : never
    : never;
