/**
 * Public Trees Error Taxonomy (P30-T13, P30-T18, P30-T24)
 */

export const PUBLIC_TREE_ERROR_CODES = {
  NOT_AVAILABLE: "PUBLIC_TREE_NOT_AVAILABLE",
  NOT_FOUND: "PUBLIC_TREE_NOT_FOUND",
  VISIBILITY_INVALID: "PUBLIC_TREE_VISIBILITY_INVALID",
  SLUG_INVALID: "PUBLIC_TREE_SLUG_INVALID",
  SLUG_CONFLICT: "PUBLIC_TREE_SLUG_CONFLICT",
  PUBLISH_FORBIDDEN: "PUBLIC_TREE_PUBLISH_FORBIDDEN",
  UNPUBLISH_FORBIDDEN: "PUBLIC_TREE_UNPUBLISH_FORBIDDEN",
  VERSION_CONFLICT: "PUBLIC_TREE_VERSION_CONFLICT",
  PROJECTION_FAILED: "PUBLIC_PROJECTION_FAILED",
  PROJECTION_VERSION_UNSUPPORTED: "PUBLIC_PROJECTION_VERSION_UNSUPPORTED",
  PERSON_NOT_AVAILABLE: "PUBLIC_PERSON_NOT_AVAILABLE",
  PERSON_REDACTION_FAILED: "PUBLIC_PERSON_REDACTION_FAILED",
  BRANCH_HIDDEN: "PUBLIC_BRANCH_HIDDEN",
  GRAPH_CENTER_INVALID: "PUBLIC_GRAPH_CENTER_INVALID",
  GRAPH_BOUNDARY_INVALID: "PUBLIC_GRAPH_BOUNDARY_INVALID",
  GRAPH_CROSS_TREE: "PUBLIC_GRAPH_CROSS_TREE",
  GRAPH_LIMIT_EXCEEDED: "PUBLIC_GRAPH_LIMIT_EXCEEDED",
  GRAPH_TOPOLOGY_INVALID: "PUBLIC_GRAPH_TOPOLOGY_INVALID",
  GRAPH_DANGLING_EDGE: "PUBLIC_GRAPH_DANGLING_EDGE",
  MEDIA_NOT_AVAILABLE: "PUBLIC_MEDIA_NOT_AVAILABLE",
  MEDIA_FORBIDDEN: "PUBLIC_MEDIA_FORBIDDEN",
  CACHE_NAMESPACE_MISMATCH: "PUBLIC_CACHE_NAMESPACE_MISMATCH",
  GUEST_MUTATION_FORBIDDEN: "PUBLIC_GUEST_MUTATION_FORBIDDEN",
  RATE_LIMITED: "PUBLIC_RATE_LIMITED",
  UNKNOWN_ERROR: "P30_UNKNOWN_ERROR",
} as const;

export type PublicTreeErrorCode =
  (typeof PUBLIC_TREE_ERROR_CODES)[keyof typeof PUBLIC_TREE_ERROR_CODES];

const HTTP_STATUS_MAP: Record<PublicTreeErrorCode, number> = {
  [PUBLIC_TREE_ERROR_CODES.NOT_AVAILABLE]: 404,
  [PUBLIC_TREE_ERROR_CODES.NOT_FOUND]: 404,
  [PUBLIC_TREE_ERROR_CODES.VISIBILITY_INVALID]: 400,
  [PUBLIC_TREE_ERROR_CODES.SLUG_INVALID]: 400,
  [PUBLIC_TREE_ERROR_CODES.SLUG_CONFLICT]: 409,
  [PUBLIC_TREE_ERROR_CODES.PUBLISH_FORBIDDEN]: 403,
  [PUBLIC_TREE_ERROR_CODES.UNPUBLISH_FORBIDDEN]: 403,
  [PUBLIC_TREE_ERROR_CODES.VERSION_CONFLICT]: 409,
  [PUBLIC_TREE_ERROR_CODES.PROJECTION_FAILED]: 500,
  [PUBLIC_TREE_ERROR_CODES.PROJECTION_VERSION_UNSUPPORTED]: 400,
  [PUBLIC_TREE_ERROR_CODES.PERSON_NOT_AVAILABLE]: 404,
  [PUBLIC_TREE_ERROR_CODES.PERSON_REDACTION_FAILED]: 500,
  [PUBLIC_TREE_ERROR_CODES.BRANCH_HIDDEN]: 403,
  [PUBLIC_TREE_ERROR_CODES.GRAPH_CENTER_INVALID]: 400,
  [PUBLIC_TREE_ERROR_CODES.GRAPH_BOUNDARY_INVALID]: 400,
  [PUBLIC_TREE_ERROR_CODES.GRAPH_CROSS_TREE]: 403,
  [PUBLIC_TREE_ERROR_CODES.GRAPH_LIMIT_EXCEEDED]: 422,
  [PUBLIC_TREE_ERROR_CODES.GRAPH_TOPOLOGY_INVALID]: 422,
  [PUBLIC_TREE_ERROR_CODES.GRAPH_DANGLING_EDGE]: 422,
  [PUBLIC_TREE_ERROR_CODES.MEDIA_NOT_AVAILABLE]: 404,
  [PUBLIC_TREE_ERROR_CODES.MEDIA_FORBIDDEN]: 403,
  [PUBLIC_TREE_ERROR_CODES.CACHE_NAMESPACE_MISMATCH]: 500,
  [PUBLIC_TREE_ERROR_CODES.GUEST_MUTATION_FORBIDDEN]: 403,
  [PUBLIC_TREE_ERROR_CODES.RATE_LIMITED]: 429,
  [PUBLIC_TREE_ERROR_CODES.UNKNOWN_ERROR]: 500,
};

const USER_MESSAGES: Record<PublicTreeErrorCode, string> = {
  [PUBLIC_TREE_ERROR_CODES.NOT_AVAILABLE]:
    "Cây gia phả công khai không tồn tại hoặc đã được chuyển sang chế độ riêng tư.",
  [PUBLIC_TREE_ERROR_CODES.NOT_FOUND]: "Không tìm thấy cây gia phả.",
  [PUBLIC_TREE_ERROR_CODES.VISIBILITY_INVALID]: "Mức độ riêng tư không hợp lệ.",
  [PUBLIC_TREE_ERROR_CODES.SLUG_INVALID]:
    "Đường dẫn công khai (slug) không hợp lệ. Chỉ chấp nhận chữ cái thường, số và dấu gạch ngang (3-60 ký tự).",
  [PUBLIC_TREE_ERROR_CODES.SLUG_CONFLICT]:
    "Đường dẫn công khai (slug) này đã được sử dụng bởi một cây gia phả khác.",
  [PUBLIC_TREE_ERROR_CODES.PUBLISH_FORBIDDEN]:
    "Chỉ Chủ sở hữu (Owner) mới có quyền công khai cây gia phả.",
  [PUBLIC_TREE_ERROR_CODES.UNPUBLISH_FORBIDDEN]:
    "Chỉ Chủ sở hữu (Owner) mới có quyền chuyển cây gia phả về riêng tư.",
  [PUBLIC_TREE_ERROR_CODES.VERSION_CONFLICT]:
    "Cài đặt cây gia phả đã được chỉnh sửa ở nơi khác. Vui lòng tải lại trang và thử lại.",
  [PUBLIC_TREE_ERROR_CODES.PROJECTION_FAILED]: "Lỗi xử lý dữ liệu chiếu công khai.",
  [PUBLIC_TREE_ERROR_CODES.PROJECTION_VERSION_UNSUPPORTED]: "Phiên bản chiếu không được hỗ trợ.",
  [PUBLIC_TREE_ERROR_CODES.PERSON_NOT_AVAILABLE]: "Thông tin nhân vật này không khả dụng.",
  [PUBLIC_TREE_ERROR_CODES.PERSON_REDACTION_FAILED]: "Lỗi bảo vệ dữ liệu cá nhân.",
  [PUBLIC_TREE_ERROR_CODES.BRANCH_HIDDEN]: "Nhánh này bị ẩn do chính sách riêng tư.",
  [PUBLIC_TREE_ERROR_CODES.GRAPH_CENTER_INVALID]: "Nhân vật trung tâm không hợp lệ.",
  [PUBLIC_TREE_ERROR_CODES.GRAPH_BOUNDARY_INVALID]: "Ranh giới nhánh không hợp lệ.",
  [PUBLIC_TREE_ERROR_CODES.GRAPH_CROSS_TREE]: "Yêu cầu vi phạm ranh giới cây gia phả.",
  [PUBLIC_TREE_ERROR_CODES.GRAPH_LIMIT_EXCEEDED]: "Độ sâu đồ thị vượt quá giới hạn an toàn.",
  [PUBLIC_TREE_ERROR_CODES.GRAPH_TOPOLOGY_INVALID]: "Cấu trúc đồ thị không hợp lệ.",
  [PUBLIC_TREE_ERROR_CODES.GRAPH_DANGLING_EDGE]: "Liên kết quan hệ không hợp lệ.",
  [PUBLIC_TREE_ERROR_CODES.MEDIA_NOT_AVAILABLE]: "Tệp hình ảnh không khả dụng.",
  [PUBLIC_TREE_ERROR_CODES.MEDIA_FORBIDDEN]: "Bạn không có quyền xem tệp hình ảnh này.",
  [PUBLIC_TREE_ERROR_CODES.CACHE_NAMESPACE_MISMATCH]: "Lỗi phân tách bộ nhớ tạm công khai.",
  [PUBLIC_TREE_ERROR_CODES.GUEST_MUTATION_FORBIDDEN]:
    "Khách xem công khai chỉ có quyền đọc, không được phép thay đổi dữ liệu.",
  [PUBLIC_TREE_ERROR_CODES.RATE_LIMITED]: "Tần suất yêu cầu quá nhanh. Vui lòng thử lại sau.",
  [PUBLIC_TREE_ERROR_CODES.UNKNOWN_ERROR]: "Đã xảy ra lỗi không xác định.",
};

export class PublicTreeError extends Error {
  readonly code: PublicTreeErrorCode;
  readonly httpStatus: number;

  constructor(code: PublicTreeErrorCode, customMessage?: string) {
    super(customMessage || USER_MESSAGES[code] || USER_MESSAGES.P30_UNKNOWN_ERROR);
    this.name = "PublicTreeError";
    this.code = code;
    this.httpStatus = HTTP_STATUS_MAP[code] || 500;
  }
}
