export const BACKUP_ERROR_CODES = {
  // Export errors
  EXPORT_FORBIDDEN: "BACKUP_EXPORT_FORBIDDEN",
  TREE_NOT_FOUND: "BACKUP_TREE_NOT_FOUND",
  SNAPSHOT_INCONSISTENT: "BACKUP_SNAPSHOT_INCONSISTENT",
  SCHEMA_VALIDATION_FAILED: "BACKUP_SCHEMA_VALIDATION_FAILED",
  SECRET_DETECTED: "BACKUP_SECRET_DETECTED",
  EXPORT_TOO_LARGE: "BACKUP_EXPORT_TOO_LARGE",
  EXPORT_FAILED: "BACKUP_EXPORT_FAILED",

  // Import errors
  FILE_REQUIRED: "BACKUP_FILE_REQUIRED",
  FILE_TOO_LARGE: "BACKUP_FILE_TOO_LARGE",
  FILE_ENCODING_INVALID: "BACKUP_FILE_ENCODING_INVALID",
  JSON_INVALID: "BACKUP_JSON_INVALID",
  SCHEMA_VERSION_MISSING: "BACKUP_SCHEMA_VERSION_MISSING",
  SCHEMA_VERSION_INVALID: "BACKUP_SCHEMA_VERSION_INVALID",
  VERSION_UNSUPPORTED: "BACKUP_VERSION_UNSUPPORTED",
  VERSION_TOO_NEW: "BACKUP_VERSION_TOO_NEW",
  SCHEMA_INVALID: "BACKUP_SCHEMA_INVALID",
  SEMANTIC_INVALID: "BACKUP_SEMANTIC_INVALID",
  REFERENCE_MISSING: "BACKUP_REFERENCE_MISSING",
  DUPLICATE_ID: "BACKUP_DUPLICATE_ID",
  CYCLE_DETECTED: "BACKUP_CYCLE_DETECTED",
  MANIFEST_MISMATCH: "BACKUP_MANIFEST_MISMATCH",
  SECRET_FIELD_DETECTED: "BACKUP_SECRET_FIELD_DETECTED",
  PREVIEW_STALE: "BACKUP_PREVIEW_STALE",
  IMPORT_FORBIDDEN: "BACKUP_IMPORT_FORBIDDEN",
  IMPORT_LIMIT_EXCEEDED: "BACKUP_IMPORT_LIMIT_EXCEEDED",
  IMPORT_ROLLBACK: "BACKUP_IMPORT_ROLLBACK",
  IMPORT_FAILED: "BACKUP_IMPORT_FAILED",
  UNKNOWN_ERROR: "BACKUP_UNKNOWN_ERROR",
} as const;

export type BackupErrorCode = (typeof BACKUP_ERROR_CODES)[keyof typeof BACKUP_ERROR_CODES];

export class BackupDomainError extends Error {
  readonly code: BackupErrorCode;
  readonly status: number;
  readonly recordErrors?: any[];

  constructor(code: BackupErrorCode, message: string, status: number = 400, recordErrors?: any[]) {
    super(message);
    this.name = "BackupDomainError";
    this.code = code;
    this.status = status;
    this.recordErrors = recordErrors;
  }
}
