export const HEARTBEAT_ERROR_CODES = {
  METHOD_NOT_ALLOWED: "HEARTBEAT_METHOD_NOT_ALLOWED",
  UNAUTHORIZED: "HEARTBEAT_UNAUTHORIZED",
  SECRET_MISSING: "HEARTBEAT_SECRET_MISSING",
  SECRET_INVALID: "HEARTBEAT_SECRET_INVALID",
  PAYLOAD_INVALID: "HEARTBEAT_PAYLOAD_INVALID",
  RATE_LIMITED: "HEARTBEAT_RATE_LIMITED",
  DATABASE_UNAVAILABLE: "HEARTBEAT_DATABASE_UNAVAILABLE",
  WRITE_FAILED: "HEARTBEAT_WRITE_FAILED",
  TIMEOUT: "HEARTBEAT_TIMEOUT",
  RETRY_EXHAUSTED: "HEARTBEAT_RETRY_EXHAUSTED",
  POLICY_UNVERIFIED: "HEARTBEAT_POLICY_UNVERIFIED",
  SCHEDULE_DISABLED: "HEARTBEAT_SCHEDULE_DISABLED",
  ALERT_FAILED: "HEARTBEAT_ALERT_FAILED",
  CLEANUP_FORBIDDEN: "HEARTBEAT_CLEANUP_FORBIDDEN",
  CLEANUP_FAILED: "HEARTBEAT_CLEANUP_FAILED",
  UNKNOWN_ERROR: "HEARTBEAT_UNKNOWN_ERROR",
} as const;

export type HeartbeatErrorCode = (typeof HEARTBEAT_ERROR_CODES)[keyof typeof HEARTBEAT_ERROR_CODES];

export class HeartbeatError extends Error {
  readonly code: HeartbeatErrorCode;
  readonly httpStatus: number;

  constructor(code: HeartbeatErrorCode, message: string, httpStatus = 400) {
    super(message);
    this.name = "HeartbeatError";
    this.code = code;
    this.httpStatus = httpStatus;
  }
}
